### ISSUE TITLE
Latest Arch Linux pycodestyle package breaks flake8

### ISSUE THREAD

**Issue by pdijksta** [PyCQA/pycodestyle#756]
Hi, I hope it is correct to report this here instead of the Arch Linux bugtracker or at the flake8 project.

Since the upgrade from from pycodestyle 2.3.1 to 2.4.0, flake8 version 3.5.0 does not work any more.
Downgrading again solved the issue for me.
Now I am not sure if this is the fault of pycodestyle or flake8. I report this here since the recent upgrade caused it.

Thank you for your time. Please find below the error trace when I call flake8 in the python2 or python3 version.

 [philipp@t400 ~]$ flake8
 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in resolve
    return functools.reduce(getattr, self.attrs, module)
 AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 178, in load_plugin
    self._load(verify_requirements)
  File "/usr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 150, in _load
    self._plugin = resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2334, in resolve
    raise ImportError(str(exc))
 ImportError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
  File "/usr/bin/flake8", line 11, in <module>
    load_entry_point('flake8==3.5.0', 'console_scripts', 'flake8')()
  File "/usr/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/lib/python3.6/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/usr/lib/python3.6/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/usr/lib/python3.6/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/usr/lib/python3.6/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/usr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/usr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/usr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
 flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module  'pycodestyle' has no attribute 'break_around_binary_operator'.

 [philipp@t400 ~]$ flake8-python2 
 Traceback (most recent call last):
  File "/usr/bin/flake8-python2", line 11, in <module>
    load_entry_point('flake8==3.5.0', 'console_scripts', 'flake8')()
  File "/usr/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/usr/lib/python2.7/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/usr/lib/python2.7/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/usr/lib/python2.7/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/usr/lib/python2.7/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/usr/lib/python2.7/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/usr/lib/python2.7/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
 flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to 'module' object

**Comment by sigmavirus24** [comment]
Duplicate of #741
